pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    dir('src') {
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Build Project') {
            steps {
                script {                
                    dir('src') {
                        sh 'npm run build'
                        sh 'npm run publish'
                    }
                }
            }
        }

        stage('Update Swagger Definition at BigIP Next') {
            steps {
                dir('automation') {
                    withCredentials([usernamePassword(
                        credentialsId: 'bigipnext-access', 
                        usernameVariable: 'CM_USER', 
                        passwordVariable: 'CM_PASSWORD'
                    )]) {
                        ansiblePlaybook(
                            playbook: 'playbooks/swagger-next.yml',
                            extras: "--extra-vars 'next_user=${CM_USER} next_password=${CM_PASSWORD}'"
                        )
                    }
                }
            }
        }

        stage('Redeploy Application') {
            steps {
                script {
                    dir('automation') {
                        ansiblePlaybook(
                            playbook: 'playbooks/app-restart-deploy.yml'
                        )
                    }
                }
            }
        }
    }
}
