---
- name: Install and configure NGINX
  hosts: app
  become: true

  vars_files:
    - app_vars.yml

  handlers:
    - name: reload-nginx
      service:
        name: nginx
        state: reloaded

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure NGINX is started and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create custom NGINX configuration
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      vars:
        server_ips: "{{ app_servers }}"
      notify:
        - reload-nginx

