stages:
  - deploy

ansible_deploy:
  stage: deploy
  image: python:3.10
  variables:
    ANSIBLE_CONFIG: ansible/ansible.cfg
  before_script:
    - pip install ansible
  script: |
    ansible-playbook ansible/playbook.yml \
      --extra-vars "ansible_user=$ANSIBLE_USER ansible_password=$ANSIBLE_PASSWORD"
  only:
    - main