pipeline {
    agent any

    stages {

        stage('Update Swagger Definition at BigIP') {
            steps {
                dir('automation') {
                    withCredentials([usernamePassword(
                        credentialsId: 'bigip-access', 
                        usernameVariable: 'BIP_USER', 
                        passwordVariable: 'BIP_PASSWORD'
                    )]) {
                        ansiblePlaybook(
                            playbook: 'playbooks/scale_out.yml',
                            extras: "--extra-vars 'bigip_user=${BIP_USER} bigip_password=${BIP_PASSWORD}'"
                        )
                    }
                }
            }
        }        
    }
}
